### ISSUE TITLE
Could you clarify the role of namespace? 

### ISSUE THREAD

**Issue by hackwaly** [Octachron/orec#1]
Nice library!
I didn't understand why there's namespaces. If we all use default namespace, what's happen?

**Comment by Octachron** [comment]
All fields in a single namespace are valid for all records defined within this namespace.

Namespace allow to create groups of records and fields that are separated from each other.
For instance, with
```ocaml
module A = Orec.Namespace.Make()
let pos : int A.field = A.new_field ()
let with_pos = A.( create [ pos ^= 0 ] )
module B = Orec.Namespace.Make()
let name : string B.field = B.new_field ()
let with_name = B.( create [ name ^= "A name" ] )
```
it is possible to raise an error if one try to access the `pos` field in the `with_name` open record:
```ocaml
with_pos.B.%{name}
```
```
Error: This expression has type A.t but an expression was expected of type B.t
```
